#!/bin/sh
uci -q batch <<-EOF
	set firewall.glinet_privacy=include
	set firewall.glinet_privacy.path='/usr/libexec/glinet-privacy/fw-plugin.sh'
	set firewall.glinet_privacy.reload='1'
	set firewall.glinet_privacy.enabled='1'
EOF
uci -q delete firewall.privacy_tor 2>/dev/null || true
uci commit firewall
exit 0
