#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2026 GL.iNet Privacy contributors
[ -x /usr/libexec/glinet-privacy/apply-device-profile.sh ] && \
	/usr/libexec/glinet-privacy/apply-device-profile.sh
exit 0
