#!/bin/sh
#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2026 GL.iNet Privacy contributors
[ -x /usr/bin/apply-privacy-firewall-includes.sh ] && /usr/bin/apply-privacy-firewall-includes.sh
exit 0
