# dnsmasq domain black-hole (symlinked from /etc/dnsmasq.d when enabled in LuCI)

address=/goodcloud.xyz/0.0.0.0
address=/www.goodcloud.xyz/0.0.0.0
address=/gldns.com/0.0.0.0
address=/router.gl-inet.com/0.0.0.0
